# Generated by Django 5.2.5 on 2026-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectcategory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='BongoCore', max_length=100),
        ),
    ]
