# Generated by Django 5.2.5 on 2026-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('logo_white', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('url', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=100, help_text='Lower number = higher priority. Use 50, 100, 150 etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand/Client',
                'verbose_name_plural': 'Brands/Clients',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
